after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - '1.9'
  - 1.10.x
  - 1.11.x
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -vendor-only
language: go
script:
  - go test -v -timeout=1m -race -covermode=atomic ./...
  - go test -v -timeout=1m -cover -coverprofile=coverage.out ./...
  - go test -v -timeout=1m ./...
