# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/go-openapi/analysis"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/validate"
  version = "0.16.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
